### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by mattn** [Shinpeim/process-book#11]
markdownで書かれておられるので、gh-pagesブランチに放り込んで _config.yml を足せば https://shinpeim.github.com/process-book で閲覧可能になるかと思いますが、いかがでしょうか。

**Comment by sasaplus1** [comment]
数年前のissueにコメントするのも気が引けますが、作ってみました。
http://sasaplus1.github.io/process-book/
https://github.com/sasaplus1/process-book/tree/gh-pages

**Comment by Shinpeim** [comment]
:+1: :pray:

参考にしてアレしようと思っていて忘れていました。セルフアサインしておきます。

**Comment by Shinpeim** [comment]
しばらく README からリンク貼らせてください

**Comment by mattn** [comment]
:+1:

**Comment by Shinpeim** [comment]
とくみたらそのまままるパクリすればよいだけになっててまじ @sasaplus1 ++

PRがなんか取り込めなかったんで手動取り込みさせていただきました。

:+1: :pray: :bow: :beer: :sake:

**Comment by sasaplus1** [comment]
うおー、手早い対応ありがとうございます！:+1:

**Comment by dictav** [comment]
:+1:
